version: 2

sources:
  - name: raw_data
    database: dbt_pipeline_demo
    schema: main
    tables:
      - name: user_activity
        description: "Raw user activity data"

models:
version: 2

models:
  - name: dim_user
    description: "Dimension table for user data."
    columns:
      - name: user_id
        description: "Unique identifier for each user."
      - name: first_name
        description: "User's first name."
  - name: product_schema
    columns:
      - name: user_id
        description: "Unique identifier for each user."
        tests:
          - relationships:
              to: ref('dim_user')
              field: user_id
      - name: session_id
        description: "Primary key for the model"
        tests:
          - unique
          - not_null
    
    indexes:
      - columns: ['user_id']
      - columns: ['login_time']
      - columns: ['product_name']