version: 2

sources:
  - name: raw_data
    database: dbt_pipeline_demo
    schema: main
    tables:
      - name: user_activity

models:
  - name: dim_user
    description: "Dimension table for user data"
    columns:
      - name: user_id
        description: "Unique identifier for each user."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "User's first name."
      - name: last_name
        description: "User's last name."
      - name: email
        description: "User's email address."
      - name: is_active
        description: "Whether the user is active."
  
  - name: stg_product_schema
    description: "Staging table for product data"
    columns:
      - name: user_id
        description: "Unique identifier for each user."
        tests:
          - unique
          - not_null

  - name: product_schema
    description: "Production product data"
    schema: main
    columns:
      - name: session_id
        description: "Unique identifier for each session"
        tests:
          - unique
          - not_null
      - name: user_id
        description: "Foreign key to the user dimension table"
        tests:
          - not_null
          - relationships:
              to: ref('dim_user')
              field: user_id
      - name: price
        description: "Price of the product"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 5000

    indexes:
      - columns: ['user_id']
      - columns: ['login_time']
      - columns: ['product_name']