version: 2

sources:
  - name: raw_data
    schema: main
    tables:
      - name: user_activity
        description: "Raw user activity data from DuckDB"
        loaded_at_field: "account_updated"

models:
  - name: dim_user
    description: "Dimension table for user data."
    columns:
      - name: user_id
        description: "Unique identifier for each user."
        tests:
          - unique
          - not_null
      - name: first_name
        description: "User's first name."
      - name: last_name
        description: "User's last name."
      - name: email
        description: "User's email address."
      - name: is_active
        description: "Whether the user is active."

  - name: stg_product_schema
    description: "Staging table for product data"
    schema: main
    
  - name: product_schema
    description: "Production product data"
    schema: main
    depends_on:
      - ref('stg_product_schema')
    columns:
      - name: user_id
        description: "Unique identifier for each user."
        tests:
          - relationships:
              to: ref('dim_user')
              field: user_id
      - name: session_id
        description: "Primary key for the model"
        tests:
          - unique
          - not_null

    indexes:
      - columns: ['user_id']
      - columns: ['login_time']
      - columns: ['product_name']